# Generated by Django 4.2 on 2023-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(upload_to='qr_codes/')),
                ('qr_data', models.CharField(max_length=255)),
                ('scan_location', models.CharField(max_length=255)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('foreground_color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
            ],
        ),
    ]
